### ISSUE TITLE
Issue with epistatic.correlation

### ISSUE THREAD

**Issue by Palash63** [QSG-Group/WISH#5]
Hi, I was using the WISH package and ran into some issues. Here is the following

ped <- fread("./test.ped", data.table=F)
tped <- fread("./test.tped", data.table=F)
genotype <- generate.genotype(, snp.id=tped[,2], pvalue=0.05, id.select=ped[,2],gwas.p=NULL,major.freq=0.95)
1103 passed QC
phenotype <- fread("/test_pheno.txt", data.table = F)
rownames(phenotype) <- phenotype$V1
phenotype$V1 <- NULL # (thus, only one column)

correlation <- epistatic.correlation(phenotype$V2,genotype,threads=1,test=T,simple=F,glm=F)
Running Test
Estimating run time based on ~100.000 models
The estimated run time for the simple model is 0.12 hours
The estimated run time for the full model is 0.22 hours

However, my correlation matrix is NULL(empty). I should be supposed to get a list of 2 matrices (P-values and epistatic interaction effects). I was wondering what's wrong with my code. Thanks for your help.

**Comment by josieparis** [comment]
Hey Palash63, 

I just thought I'd comment in case you were still having a problem with this. You need to change the command to not test the computational time and actually run the correlations
```
correlation <- epistatic.correlation(phenotype$V2,genotype,threads=1,test=F,simple=F,glm=F)
```
hope that helps!

**Comment by Palash63** [comment]
Hi Josieparis,
Thanks for your suggestion. Much appreciated. My problem was resolved earlier.
